chore(deps): Testing gitlab-ci.yml

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -13,14 +13,15 @@ deploy:
       echo "CI_COMMIT_BEFORE_SHA: $CI_COMMIT_BEFORE_SHA"
       echo "CI_COMMIT_SHA: $CI_COMMIT_SHA"
       # Check if git diff command fails and exit if it does
-      if changed_tasks=$(git diff --name-only $CI_COMMIT_BEFORE_SHA $CI_COMMIT_SHA | grep "^ansible/tasks/.*\.yml$"); then
-        # Split the changed tasks into an array and iterate over them
-        IFS=$'\n' read -r -d '' -a tasks_array <<< "$changed_tasks"
-        for task in "${tasks_array[@]}"; do
-          echo "- $task"
-          echo "Running Ansible playbook for $task..."
-          # Add your Ansible playbook execution command here for each task
-        done
+      if ! changed_tasks=$(git diff --name-only $CI_COMMIT_BEFORE_SHA $CI_COMMIT_SHA | grep "^ansible/tasks/.*\.yml$"); then
+        echo "Error: Failed to run git diff command"
+        exit 1
+      fi
+      if [ -n "$changed_tasks" ]; then
+        updated_task=$(echo "$changed_tasks" | head -n 1)  
+        echo "The following task file has been updated: $updated_task"
+        echo "Running Ansible playbook..."
+        echo "$updated_task"
       else
         echo "No changes detected in task files. Skipping Ansible playbook execution."
       fi
